### ISSUE TITLE
Again from my github

### ISSUE THREAD

**Issue by BeastGB** [AngelWasTaken/Original-Codegen-Utilla#1]
I was the first original person to fucking distribute codegen and gorillautils after it was taken down

These are mine because i named them with all uppercases

at least credit me

Or if you stop being dumb and figure out you can't patch on latest builds TAKE IT DOWN!!!

**Comment by AngelWasTaken** [comment]
no. you wern't the first person to distribute the core mods, you do not own any kind of copywrite for these mods, they wern't even made by you so I will not be taking these down

**Comment by AngelWasTaken** [comment]
and how is the name proof that they were yours? I have most of the original gorilla tag mods archived in a usb drive

**Comment by BeastGB** [comment]
I named it all caps

I just want people to credit me when they take it from my github

I didn't say I was the first to EVER post them, I said i was the first to post them when they were taken down

**Comment by AngelWasTaken** [comment]
"I was the first original person to fucking distribute codegen and gorillautils after it was taken down"

I also did not take them from your github.
